<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Version>1.6.0-alpha.6</Version>
    <OutputType>Library</OutputType>
    <TargetFramework>net471</TargetFramework>
    <LangVersion>11</LangVersion>
    <CodeAnalysisRuleSet>$(MSBuildThisFileDirectory)rules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

  <PropertyGroup>
    <!-- avoids IgnoresAccessChecksToAttribute warnings -->
    <PublicizerRuntimeStrategies>Unsafe</PublicizerRuntimeStrategies>
  </PropertyGroup>

  <PropertyGroup>
    <DLLPathLocal>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)..\..\BT-Mod-Dependencies\libs'))</DLLPathLocal>
    <DLLPathCI>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)..\BT-Mod-Dependencies\libs'))</DLLPathCI>

    <DLLPath Condition="Exists('$(DLLPathLocal)')">$(DLLPathLocal)</DLLPath>
    <DLLPath Condition=" '$(DLLPath)' == '' ">$(DLLPathCI)</DLLPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Krafs.Publicizer" Version="2.2.1" />
    <Publicize Include="Assembly-CSharp" />
    <Publicize Include="DOTween;DOTweenPro" />
    <Publicize Include="UnityEngine.CoreModule" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="8.0.0" PrivateAssets="all" />
    <PackageReference Include="Roslynator.Analyzers" Version="4.12.0" PrivateAssets="all" />
  </ItemGroup>

  <!-- <PropertyGroup>
    <DebugType>full</DebugType>
  </PropertyGroup> -->

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>$(DLLPath)\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(DLLPath)\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(DLLPath)\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ParticleSystemModule">
      <HintPath>$(DLLPath)\UnityEngine.ParticleSystemModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(DLLPath)\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AssetBundleModule">
      <HintPath>$(DLLPath)\UnityEngine.AssetBundleModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TerrainModule">
      <HintPath>$(DLLPath)\UnityEngine.TerrainModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>$(DLLPath)\Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>$(DLLPath)\UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AnimationModule">
      <HintPath>$(DLLPath)\UnityEngine.AnimationModule.dll</HintPath>
    </Reference>
    <Reference Include="Dapper.Unity">
      <HintPath>$(DLLPath)\Dapper.Unity.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(DLLPath)\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="System">
      <HintPath>$(DLLPath)\System.dll</HintPath>
    </Reference>
    <Reference Include="System.Numerics">
      <HintPath>$(DLLPath)\System.Numerics.dll</HintPath>
    </Reference>
    <Reference Include="System.Core">
      <HintPath>$(DLLPath)\System.Core.dll</HintPath>
    </Reference>
    <Reference Include="System.Data">
      <HintPath>$(DLLPath)\System.Data.dll</HintPath>
    </Reference>
    <Reference Include="System.Runtime.Serialization">
      <HintPath>$(DLLPath)\System.Runtime.Serialization.dll</HintPath>
    </Reference>
    <Reference Include="InControl">
      <HintPath>$(DLLPath)\InControl.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>$(DLLPath)\Newtonsoft.Json.dll</HintPath>
      <Private>True</Private>
    </Reference>
  </ItemGroup>

</Project>
